In [ ]:
# 1 var = 1 value
name = 'ramesh'

names = ['ramesh', 'suresh', 25, (1,2,3), ('dan', 'michelle'), {'fn':'John', 'ln': 'Rambo', 'mobile': 99886655}]

names[5].get('fn')

In [ ]:
num = (5,8,9,4,6)
print('tuple data - ', num)

setNum = {5,8,9,4,6}
print('set data - ', setNum)

In [ ]:
# List
t1 = [3,2,8,5,6,4,7,5]
t2 = [34,56,76,89,3,2,8]
t3 = [4,5]

# print(type(t1))

#concatinate
# t1 + t2 

# repeation
# t3 * 2

# membership
# 5 in t2
# 5 in t1

# indexing
# t1[3]

# slicing
# t1[slice(6)]

# length
print('lenght of t1 = ',len(t1))

# List operations
print("before - " ,t1)
# t1.append(65)
# t1[2] = 55
# del t1[5]
# t1.clear()
# x = t1.copy()
# print('count = ', t1.count(7))
# t1.extend(t2)
# print('index of 4 is ',t1.index(4))
# t1.insert(0,25)
# t1.insert(2, 56)
# t1.insert(8, 99)
t1.insert(len(t1),99)
# t1.pop()
# t1.remove(7) # removing single value
# t1.remove(5) # if the value is duplicated, it will remove the first occurence
# t1.reverse()
# t1.sort()



print("after - " ,t1)

In [ ]:
# tuple
t1 = (3,2,8,5,6,4,7,5)
t2 = (34,56,76,89,3,2,8)
t3 = (4,5)

# print(type(t1))
print(t1)

#concatinate
# t1 + t2 

# repeation
# t3 * 2

# membership
# 5 in t2
# 5 in t1

# indexing
# t1[3]

# slicing
t1[slice(6)]

# length
# print('lenght of t1 = ',len(t1))

# tupe operations
# print("before - " ,t1)
# print('count = ', t1.count(5))
# print('index of 4 is ',t1.index(4))



# print("after - " ,t1)

In [42]:
# set

t1 = {3,2,8,5,6,4,7,5}
t2 = {34,56,76,89,3,2,8}
t3 = {4,5}


# print(type(t1))
# print(t1)
# print(t2)
# print(t3)


# membership
# 5 in t2
# 5 in t1

# length
# print('lenght of t1 = ',len(t1))

# set operations
# print("before - " ,t1)
# t1.add(55)
# t1.clear()
# x = t1.copy()
# print("x = ", x)

# print("t1 = ",t1)
# print("t2 = ", t2)
# print('difference = ',t1.difference(t2))
# print('difference = ',t2.difference(t1))

# x = {1,2,3}
# y = {4,5,2}
# y.difference_update(x)
# print("after x = ", y)

# t1.discard(6)

# x = {1,2,3}
# y = {4,5,2}
# t1.intersection(x)
# print("after intersection, x = ",t1)

x = {1,2,3}
y = {4,5,2}
z = {6,9}
x.intersection_update(y)
# print("after intersection update, x = ", x)


# ************************start from here*********************
# x.isdisjoint(z)



# print('count = ', t1.count(5))
# print('index of 4 is ',t1.index(4))


# print("after - " ,t1)

a = {1,2,3,4,5}
b = {1,2,5}
c = {1,2,5}
# print('a is subset of b? ', a.issubset(b))
# print('b is subset of a? ', b.issubset(a))

# print('a is superset of b? ', a.issuperset(b))
# print('b is superset of a? ', b.issuperset(a))

# b.issubset(c)
# c.issubset(b)
# b.issuperset(c)
# c.issuperset(b)

# c.issubset(c)
# c.issuperset(c)

# print(a.pop())
# print(a)

a.symmetric_difference(b)
b.symmetric_difference_update(a)



print(a)
print(b)

{1, 2, 3, 4, 5}
{3, 4}

In [35]:
l1={'192.168.1.1', '192.168.1.2', '192.168.1.3', '192.168.1.4', '192.168.1.5', '192.168.1.6', '192.168.1.7', '192.168.1.8', '192.168.1.9', '192.168.1.10', '192.168.1.11', '192.168.1.12', '192.168.1.13', '192.168.1.14', '192.168.1.15', '192.168.1.16', '192.168.1.17', '192.168.1.18', '192.168.1.19', '192.168.1.20', '192.168.1.21', '192.168.1.22', '192.168.1.23', '192.168.1.24', '192.168.1.25', '192.168.1.26'}
l2 ={'192.168.1.3', '192.168.1.7', '192.168.1.56'}

# l2.issubset(l1)
l1.issuperset(l2)

False

In [119]:
# dict
a = {'fn':'John', 'ln':'Rambo'}
b = {'mobile':9886098860, 'email':'john@gmail.com'}

a.update({'city':'london'})


print(a)
print(sorted(a))
# a.update(b)

# a.clear()
# print(a)

# c = a.copy()
# c = b.copy()
# print(c)

# t= ('a', 'b', 'c')
# d.fromkeys(t, 25)

# print(a.get('fn', 'not applicable'))

# print(a.items())
# z = a.keys()
# print(z)
# for i in z:
#     print(i)

# z = a.values()
# print(z)
# for i in z:
#     print(i)

# z = a.keys()
# for i in z:
#     print('key = {} , value={}'.format(i, a.get(i)))

# print(a.pop('fn'))
# print(a)

# c = a.copy()
# c.update(b)
# print(c)

# a['fn'] = 'Michelle'
# print(a)

# print(a)
# a['email'] = 'rambo@gmail.com'
# print(a)

# print(a)
# print(a.get('xyz', 'NA'))
# print(a.setdefault('fn', 'NA'))
# print(a.setdefault('asdfas'))


# print(a+b) # not possible
# print(a*2) # not possible
# print('mobile' in a)
# print('fn' in a)
# a[0]
# print(type(a))

# type({'city':'london'})

{'fn': 'John', 'ln': 'Rambo', 'city': 'london'}
['city', 'fn', 'ln']

In [2]:
l1 = {'192.168.1.1':'7.1','192.168.1.2':'7.2','192.168.1.3':'7.2','192.168.1.4':'7.3','192.168.1.5':'7.1','192.168.1.6':'7.3','192.168.1.7':'7.2'}

v71 = []
v72 = []
v73 = []

x = l1.keys()
for i in x:
    if l1.get(i) == '7.1':
        v71.append(i)
    elif l1.get(i) == '7.2':
        v72.append(i)
    else:
        v73.append(i)

print('7.1 update server - ' , v71)
print('7.2 update server - ' , v72)
print('7.3 update server - ' , v73)

7.1 update server -  ['192.168.1.1', '192.168.1.5']
7.2 update server -  ['192.168.1.2', '192.168.1.3', '192.168.1.7']
7.3 update server -  ['192.168.1.4', '192.168.1.6']

In [195]:
import math

# numbers
# a = 5

# print(a**6)
# print(pow(a, 6))

# abs(-5)
# math.modf(5)

# max(25, 55, 2)

# a = 78
# del a
# print(a)

# x = input("enter the number")
# print("The value of x is ", x)
# print('The type of x is ', type(eval(x)))
# print(int(x))


x = eval(input("Enter the number"))
# x = input("Enter the number")
print('Data type associated wth x - ',type(x))
print("The value of x = ",x)
print("Int value of x is ", int(x))

# a = 7
# print(a*5)
# print(str(a)*5)

Enter the number 42949672951111122255663322565352365

Data type associated wth x -  <class 'int'>
The value of x =  42949672951111122255663322565352365
Int value of x is  42949672951111122255663322565352365

In [176]:
# Strings

# name = 'raMeshrrrr'

# name.capitalize()
# name.casefold()
# name.center(4)
# name.count('r')
# name.endswith('t')
# name.isalnum()

True