In [ ]:
# 1 var = 1 value
name = 'ramesh'

names = ['ramesh', 'suresh', 25, (1,2,3), ('dan', 'michelle'), {'fn':'John', 'ln': 'Rambo', 'mobile': 99886655}]

names[5].get('fn')

In [ ]:
num = (5,8,9,4,6)
print('tuple data - ', num)

setNum = {5,8,9,4,6}
print('set data - ', setNum)

In [ ]:
# List
t1 = [3,2,8,5,6,4,7,5]
t2 = [34,56,76,89,3,2,8]
t3 = [4,5]

# print(type(t1))

#concatinate
# t1 + t2 

# repeation
# t3 * 2

# membership
# 5 in t2
# 5 in t1

# indexing
# t1[3]

# slicing
# t1[slice(6)]

# length
print('lenght of t1 = ',len(t1))

# List operations
print("before - " ,t1)
# t1.append(65)
# t1[2] = 55
# del t1[5]
# t1.clear()
# x = t1.copy()
# print('count = ', t1.count(7))
# t1.extend(t2)
# print('index of 4 is ',t1.index(4))
# t1.insert(0,25)
# t1.insert(2, 56)
# t1.insert(8, 99)
t1.insert(len(t1),99)
# t1.pop()
# t1.remove(7) # removing single value
# t1.remove(5) # if the value is duplicated, it will remove the first occurence
# t1.reverse()
# t1.sort()



print("after - " ,t1)

In [ ]:
# tuple
t1 = (3,2,8,5,6,4,7,5)
t2 = (34,56,76,89,3,2,8)
t3 = (4,5)

# print(type(t1))
print(t1)

#concatinate
# t1 + t2 

# repeation
# t3 * 2

# membership
# 5 in t2
# 5 in t1

# indexing
# t1[3]

# slicing
t1[slice(6)]

# length
# print('lenght of t1 = ',len(t1))

# tupe operations
# print("before - " ,t1)
# print('count = ', t1.count(5))
# print('index of 4 is ',t1.index(4))



# print("after - " ,t1)

In [7]:
# set

t1 = {3,2,8,5,6,4,7,5}
t2 = {34,56,76,89,3,2,8}
t3 = {4,5}

# print(type(t1))
# print(t1)
# print(t2)
# print(t3)


# membership
# 5 in t2
# 5 in t1

# length
# print('lenght of t1 = ',len(t1))

# set operations
print("before - " ,t1)
# t1.add(55)
# t1.clear()
# x = t1.copy()
# print("x = ", x)

# print("t1 = ",t1)
# print("t2 = ", t2)
# print('difference = ',t1.difference(t2))
# print('difference = ',t2.difference(t1))

# x = {1,2,3}
# y = {4,5,2}
# y.difference_update(x)
# print("after x = ", y)

# t1.discard(6)

# x = {1,2,3}
# y = {4,5,2}
# t1.intersection(x)
# print("after intersection, x = ",t1)

x = {1,2,3}
y = {4,5,2}
x.intersection_update(y)
print("after intersection update, x = ", x)


# ************************start from here*********************
t1.isdisjoint

# print('count = ', t1.count(5))
# print('index of 4 is ',t1.index(4))


print("after - " ,t1)

before -  {2, 3, 4, 5, 6, 7, 8}
after intersection update, x =  {2}
after -  {2, 3, 4, 5, 6, 7, 8}